### PR TITLE
Factorization methods

### PR DESCRIPTION
**Pull request by paraynaud**

### CODE REVIEW

**Review by dpo — APPROVED** [review]

**Comment by paraynaud** [comment]
This PR save the factorization methods, we said that don't incude them in the v0.1.0.
The state of the PR is odd, since master changed and it doesn't seems to have the change of the factorization.
I'm adding the files related to the factorizations.

**Comment by paraynaud** [comment]
The conflicts are inevitable for now.

**Comment by dpo** [comment]
Why are they inevitable? This PR cannot be merged if there are conflicts.

**Comment by dpo** [comment]
What is the status of this PR compared to #35 ? I'm a bit lost.

**Comment by paraynaud** [comment]
It is in a weird state, I'm fixing it now.

**Comment by paraynaud** [comment]
It is a orthogonal work to #35 .
The current PR get factorizations files.
It still runs the tests and the documentation, so there is many files modified by that.

**Pull request closed without merging**
