### PR TITLE
use strict=true in docs

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
What were the `linkcheck` errors specifically? Ideally, we should leave it to `true`.

**Comment by paraynaud** [comment]
For any link in the `docs` subrepository I got an error similar to:
```julia
┌ Error: `curl -sI --proto =http,https,ftp,ftps https://github.com/JuliaSmoothOptimizers/PartitionedStructures.jl --max-time 10 -o nul --write-out '%{http_code} %{url_effective} %{redirect_url}'` failed:
│   exception =
│    failed process: Process(`curl -sI --proto =http,https,ftp,ftps https://github.com/JuliaSmoothOptimizers/PartitionedStructures.jl --max-time 10 -o nul --write-out '%{http_code} %{url_effective} %{redirect_url}'`, ProcessExited(35)) [35]│ 
```
This example of error is for the link `[PartitionedStructures.jl](https://github.com/JuliaSmoothOptimizers/PartitionedStructures.jl)`.
These errors prevent the documentation build.

**Comment by dpo** [comment]
Could you set it to `true` again so we can see the failure in the Action?

**Comment by dpo** [comment]
Documenter is right: https://github.com/JuliaSmoothOptimizers/PartitionedKnetNLPModels.jl does not exist.

**Comment by paraynaud** [comment]
> Documenter is right: https://github.com/JuliaSmoothOptimizers/PartitionedKnetNLPModels.jl does not exist.

There was a link https://github.com/JuliaSmoothOptimizers/PartitionedKnetNLPModels.jl in the README.md, but the last commit remove it.
I don't know where the error comes from (since there is no https://github.com/JuliaSmoothOptimizers/PartitionedKnetNLPModels.jl anymore)

**Comment by dpo** [comment]
https://github.com/JuliaSmoothOptimizers/PartitionedStructures.jl/runs/7691709665?check_suite_focus=true#step:5:13

Run it locally to check

**Comment by paraynaud** [comment]
I don't understand how things work...
Locally, I get different errors than those we get on github:
```julia 
┌ Error: `curl -sI --proto =http,https,ftp,ftps https://github.com/JuliaSmoothOptimizers/PartitionedStructures.jl --max-time 10 -o nul --write-out '%{http_code} %{url_effective} %{redirect_url}'` failed:
│   exception =
│    failed process: Process(`curl -sI --proto =http,https,ftp,ftps https://github.com/JuliaSmoothOptimizers/PartitionedStructures.jl --max-time 10 -o nul --write-out '%{http_code} %{url_effective} %{redirect_url}'`, ProcessExited(35)) [35]│ 
```

But I checked (Crtl+Shift+F) that I do not have any https://github.com/JuliaSmoothOptimizers/PartitionedKnetNLPModels.jl in the repository.

**Comment by paraynaud** [comment]
@dpo I made it work!
There was a https://github.com/JuliaSmoothOptimizers/PartitionedKnetNLPModels.jl link in the main branch, which was added by me last week when I fixed the errored links of README and index.md.
I did a rebase and I fixed the link, now it works.

Remark: I keep getting the same errors locally.

**Comment by dpo** [comment]
Thank you!

**Pull request merged**
