### PR TITLE
PartitionedVectors

### PR DESCRIPTION
**Pull request by paraynaud**
WIP, broadcast! must be rework, no test for now.

### CODE REVIEW

**Comment by paraynaud** [comment]
I implemented a half-working version of what we want.
I pushed it to save it before I rework how broadcast works.

In the current version:
```julia
N = 15
n = 20
nie = 5
element_variables =
  vcat(map((i -> sample(1:n, nie, replace = false)), 1:(N - 1)), [[4, 8, 12, 16, 20]])
epv = create_epv(element_variables; type=Float32) 
pv32 = PartitionedVector(element_variables; T=Float32)
pv_x = similar(pv32)
pv_y = similar(pv32)
pv_xy = similar(pv32)
```
create `PartitionedVector`s.
I tried to conciliate `Vector` and `PartitionedVector` in such way:
```julia
x = [1.:1:n;]
y = [2.:1:n+1;]

pv_x .= x
pv_y .= y
```
where each element of `pv_x` equals $U_i$`x`.
As long a the `=` right side is a vector, it works:
```julia
pv_xy .= x .+ y
```
but the current limitation is that 
```julia
.- pv_y
```
which broadcast `-` over `pv_y` returns a `Vector` instead of a `PartitionedVector` (same with `pv_x .+ pv_y`).

I plan to rework all of this by [customizing the `broadcast`](https://docs.julialang.org/en/v1/manual/interfaces/#man-interfaces-broadcasting-1) detailled [also here](https://discourse.julialang.org/t/how-to-customize-the-new-broadcasting-infrastructure-in-v0-7/11322/4) and following an [example about Polynomials](https://www.infty.nl/broadcast-for-inplace-polynomials.html)

I will not try to conciliate `Vector` and `PartitionedVector` anymore, but I'll make sure they work with `cg`.

**Comment by paraynaud** [comment]
@dpo, I made it work for some of the required operations, see the tests:
```julia
  N = 15
  n = 20
  nie = 5
  element_variables =
    vcat(map((i -> sample(1:n, nie, replace = false)), 1:(N - 1)), [[1, 8, 12, 16, 20]])

  epv = create_epv(element_variables; type=Float32)
  _pv32 = PartitionedVector(epv)
  pv32 = PartitionedVector(element_variables; T=Float32)

  pv64 = PartitionedVector(element_variables)

  pv_sim = similar(pv32)
  pv_copy = copy(pv32)
  pv_res = copy(pv32)

  pv_copy .= pv32 .+ pv32
  pv_res .= pv_copy .- pv32

  @test pv_res == pv32
  @test pv_res == -pv32 + pv32 + pv32
```

I spoke with Alexis about `CgSolver` and how I could make `cg!` works with `PartitionedVectors`.
For now, it seems that the best way to handle it is to define a `CgSolver` constructor dedicated to `PartitionedVectors` and implement operations required by `cg`.

https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/156522b0567e95f99d87604e5801a7037b774de7/src/krylov_utils.jl#L227

**Comment by paraynaud** [comment]
For now:
```julia
mutable struct PartitionedVector{T} <: DenseVector{T} # for Krylov
  epv::Elemental_pv{T}  
end
```

For the needs of `cg` and `trunk`, we need two types of `PartitionedVector`:
- those representing element variables : `pv_x, pv_s`, where each element vector is respectively $U_i x$ or $U_i s$.
`nlp.meta.x0` from a PSNLPModel is such a `PartitionedVector`.
They will be use by `obj(psnlp, pv_x)` or `grad(pv_g, psnlp, pv_x)`;
- those stocking and accumulating element vectors : `pv_g, pv_y`.

The methods differ depending which kind of `PartitionedVector`s are used:
- `norm` : `norm(pv_x, 2) = norm(pv_x.epv.v, 2)` while `norm(pv_g, 2) = begin build_v!(pv_g.epv); norm(pv_g.epv.v, 2) end`
- `dot` : `dot(pv_x, pv_s) = dot(pv_x.epv.v, pv_s.epv.v)` differs to `dot(pv_g, pv_s)` required in $m_k(s)$, because 
$$g^\top s = (\sum\_{i=1}^N U_i^\top \hat{g}\_i)^\top s = \sum\_{i=1}^N \hat{g}\_i^\top U_i s = \sum\_{i=1}^N \hat{g}\_i^\top \hat{s}_i$$

accumulates element vectors `dot`.
Note that `dot(pv_g, pv_y)` is not the same either, it has to accumuate element vectors dot depending the partitioned structure of the partitioned vectors 

$$ (\sum_i U_i^\top \hat{g}_i)^\top  (\sum_j U_j^\top \hat{v}_j)= \sum_i \hat{g}_i^\top U_i . \sum_j U_j^\top \hat{v}_j = \sum_i \sum_j \hat{g}_i^\top U_i U_j^\top \hat{v}_j $$

The best way to handle it seems (to me) add a `Bool` field distinguishing `PartitionedVector`s:
```julia
mutable struct PartitionedVector{T} <: DenseVector{T} # for Krylov
  epv::Elemental_pv{T}  
  simulate_vector::Bool
end
```
where `simulate_vector` is finally set at the allocation of the `PartitionedVector`

The next obstacle is to adapt `CgSolver` and `TrunkSolver` to partitioned structures.
I already defined a hand made `CgSolver`, but `TrunkSolver` and how it calls `CgSolver()` need to be redefine, maybe with a `TrunkSolver(::PartiallySeparableNLPModel)`.

```julia

  import Krylov.CgSolver

  function CgSolver(pv::PartitionedVector{T}) where T  
    Δx = PartitionedVector([[1]]; T=T)
    x  = similar(pv)
    r  = similar(pv)
    p  = similar(pv)
    Ap = similar(pv)
    z = PartitionedVector([[1]]; T=T)
    stats = Krylov.SimpleStats(0, false, false, T[], T[], T[], "unknown")
    solver = Krylov.CgSolver{T,T,PartitionedVector{T}}(Δx, x, r, p, Ap, z, false, stats)
    return solver
  end
```

**Comment by paraynaud** [comment]
@dpo, I think this one is ready for a review.
It is the first out of 3.
It adds some code which are required by the [PartitionedVectors.jl pull-request](https://github.com/paraynaud/PartitionedVectors.jl/pull/3).

**Comment by paraynaud** [comment]
It mainly implements `+, -, *` for partitioned vectors and element vectors.
It is mandatory for applying broadcast operators in PartitionedVectors.jl.

**Comment by paraynaud** [comment]
I don't know why but even if I'm installing this branch of PartitionedStructures.jl in [PartitionedVectors.jl PR](https://github.com/paraynaud/PartitionedVectors.jl/pull/3) the tests of PartitionedVectors.jl don't find pieces of code related to this branch (but it passes locally).
I think that releasing 0.1.4 and make PartitionedVectors rely on v0.1.4 should resolve this issue.

**Comment by paraynaud** [comment]
Both:
- [PartitionedVectors.jl PR](https://github.com/paraynaud/PartitionedVectors.jl/pull/3);
- [PartiallySeparableNLPModels.jl PR](https://github.com/JuliaSmoothOptimizers/PartiallySeparableNLPModels.jl/pull/59);
depend of the release that will follow this PR.

**Review by dpo — APPROVED** [review]
Great, thank you!

**Pull request merged**
