### PR TITLE
Internal partitioned structures

### PR DESCRIPTION
**Pull request by paraynaud**
This time the code is in the PR

### CODE REVIEW

**Comment by dpo** [comment]
Conflicts to resolve here.

**Comment by paraynaud** [comment]
I manually added the internal files.
Some fixes are still needed.
I will fix it in the day.
I will do the same for the factorization #31 .

Next time I will have to save functionnailities in branch, I will proceed with an other strategy.

**Comment by dpo** [comment]
It should have been enough to create branches off of `master` with `git checkout -b internal master` and `git checkout -b factorization master` to save the functionality, and then open a PR to delete the files from `master.

**Comment by paraynaud** [comment]
I did `git checkout -b factoritzation` and `git checkout -b internal` from the master branch.
But it didn't work.
Is `master` at the end of the line changing anything?

**Comment by dpo** [comment]
If you're already on `master` when you issue those commands, it's the same thing.

**Comment by dpo** [comment]
Actually, note that there is no `master` here. It's called `main`. Is that the problem?

**Comment by paraynaud** [comment]
No, I was on `main`.

**Comment by dpo** [comment]
Ok. I'm confused now. This PR seems to be *adding* the internal variables stuff to `main`. What we want to do is *remove* it.

**Comment by paraynaud** [comment]
The internal structures are already out of the `main` branch.
By merging #29, it deleted the internal structures files of the previous pull request (I don't know why).
This pull request is not meant to be accepted but rather to save the changes incorporing internal-structure files.

**Pull request closed without merging**
